//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int Cust_Id { get; set; }

        [DisplayName("Customer Name")]
       
        public string Cust_Name { get; set; }

        [DisplayName("Customer City")]
        
        public string Cust_City { get; set; }

        [DisplayName("Gender")]
       
        public string Gender { get; set; }
    }
}
