//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        public int Employee_Id { get; set; }

        [DisplayName("Employee Name")]
      
        public string Employee_Name { get; set; }

        [DisplayName("Employee Age")]
        
        public string Employee_Age { get; set; }

        [DisplayName("Employee CNIC")]
        
        public string Employee_CNIC { get; set; }


        [DisplayName("Employee Address")]
       
        public string Employee_Address { get; set; }

        [DisplayName("Employee Image")]
       
        public string EmployeeImage { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}
