//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class Product
    {
        public int Product_Id { get; set; }

        [DisplayName("Product Name")]
       

        public string Product_Name { get; set; }


        [DisplayName("Product Type")]
       

        public string Product_Type { get; set; }


        [DisplayName("Product Quantity")]
       

        public string Product_Quantity { get; set; }


        [DisplayName("Product Price")]
        

        public string Product_Price { get; set; }



        [DisplayName("Product Image")]
       // [Required(ErrorMessage  = "Product Image is Required")]
        public string ProdImage { get; set; }

        public  HttpPostedFileBase ImageFile { get; set; }
    }
}
